title: joaquinuriel.github.io

author: Joaquinuriel
email: joaquinuriel94@gmail.com

description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

remote_theme: daattali/beautiful-jekyll

avatar: /src/icons/64x64.png

navbar-links:
  index: pages/index
  about: pages/about
  calendar: pages/calendar

social-network-links:
  email: joaquinuriel94@gmail.com
  github: joaquinuriel
