title: joaquinuriel.github.io

author: Joaquinuriel
email: joaquinuriel94@gmail.com

description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

remote_theme: daattali/beautiful-jekyll

avatar: "/src/img/64x64"

navbar-links:
  About Me: "about"
  Calendar: "calendar"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

social-network-links:
  email: joaquinuriel94@gmail.com
  github: joaquinuriel
