theme: minima

minima:
  skin: dark
  social_links:
    # twitter: joaquinuriel
    github: joaquinuriel
  #   stackoverflow: "11111"
  #   dribbble: jekyll
  #   facebook: jekyll
  #   flickr: jekyll
    instagram: joaquinuriel94
  #   linkedin: jekyll
  #   pinterest: jekyll
  #   telegram: jekyll
  #   microdotblog: jekyll
  #   keybase: jekyll

header_pages:
  - pages/index.md
  - pages/about.md
  - pages/calendar.md

